'use strict';
const assert=require('node:assert/strict');
const S=require('../play-session.js');
const a=S.random('same-deal'),b=S.random('same-deal'),c=S.random('different-deal');
const one=Array.from({length:136},a),two=Array.from({length:136},b);
assert.deepEqual(one,two);assert.notDeepEqual(one,Array.from({length:136},c));
assert(one.every(n=>n>=0&&n<1));
let saved=null;
const storage={getItem:()=>saved,setItem:(key,value)=>{saved=value;}};
const history=S.create(storage);
assert.equal(history.read().length,0);
history.add({id:'first',seed:'a',net:250,pot:900,won:true,actions:[]});
history.add({id:'first',seed:'a',net:250,pot:900,won:true,actions:[]});
history.add({id:'retry',seed:'a',net:400,pot:1400,won:true,practice:true,actions:[]});
assert.deepEqual(history.stats(),{hands:1,wins:1,net:250});
assert.equal(S.create(storage).read().length,2);
for(let i=0;i<50;i++)history.add({id:'n'+i,seed:'n',net:-i,pot:900});
assert.equal(history.read().length,40);
const unavailable=S.create({getItem(){throw Error('denied');},setItem(){throw Error('denied');}});
assert.equal(unavailable.add({id:'memory',net:0,pot:0}),true);
assert.equal(unavailable.read().length,1);
assert.equal(S.create({getItem:()=>'{bad json'}).read().length,0);
assert.equal(S.describe({stage:1,selected:2}).left,12);
assert(S.describe({stage:1,selected:2}).detail.includes('あと2枚'));
assert(S.describe({stage:2,selected:4}).detail.includes('あと2枚'));
assert.equal(S.describe({stage:4,selected:14}).left,0);
assert(S.describe({stage:3,selected:6,folded:true}).title.includes('追加の支払いなし'));
console.log('PASS play-session: reproducible randomness, device-local records, deduplication, practice isolation, 40-record cap, storage denial, stage guidance');
